language: android
dist: trusty

before_install:
  - wget https://services.gradle.org/distributions/gradle-5.6.4-all.zip
  - unzip -qq gradle-5.6.4-all.zip
  - export GRADLE_HOME=$PWD/gradle-5.6.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

before_script:
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
    
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
 global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project

    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-28

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-addon-google_apis-google-28

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tools.+'
    
script:
- ./gradlew build check

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew assembleDebug
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: ./gradlew assembleGnitset
    on:
      branch: testing

  - provider: script
    skip_cleanup: true
    script: ./gradlew assembleRelease
    on:
      branch: release

  - provider: script
    skip_cleanup: true
    script: ./gradlew assembleProduction
    on:
      branch: master